name: Java CI with Maven and Selenium Tests

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # Step 3: Set up Maven (Corrected action)
      - name: Set up Maven
        uses: apache/setup-maven@v2
        with:
          maven-version: '3.9.9'


      # Step 5: Install dependencies and run tests
      - name: Build and Test with Maven
        run: mvn clean test
