name: Java CI with Maven and Selenium Tests
# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2  # Use version v2 for this action
      # Step 2: Set up Java (Temurin OpenJDK 21)
      - name: Set up Java 21
        uses: actions/setup-java@v3  # Correct version for setup-java action
        with:
          distribution: 'temurin'   # OpenJDK distribution (AdoptOpenJDK now renamed to Temurin)
          java-version: '21'        # Set the Java version to 21
          cache: 'maven'            # Cache Maven dependencies
      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository       # Maven local repository to cache dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-
      # Step 4: Build and Test with Maven
      - name: Build and Test with Maven
        run: mvn clean test           # Clean and run tests
          
      # Step 5: Optionally package the application
      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Create a Maven package (jar, war, etc.)

      - name: Upload Surefire Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports          # Name of the artifact (you can change it as needed)
          path: target/surefire-reports/  
          retention-days: 1

